export default function TermsOfService() {
    return (
        <div className="min-h-screen pt-24 pb-16 px-6 sm:px-8 lg:px-12 relative isolate">
            <div className="absolute inset-x-0 top-0 -z-10 transform-gpu overflow-hidden blur-3xl opacity-30" aria-hidden="true">
                <div className="relative left-[calc(50%-11rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 rotate-[30deg] bg-gradient-to-br from-[#8b5cf6] to-[#ec4899] sm:left-[calc(50%-30rem)] sm:w-[72.1875rem]" style={{ clipPath: 'polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)' }}></div>
            </div>

            <div className="max-w-4xl mx-auto">
                <h1 className="text-4xl sm:text-5xl font-extrabold tracking-tight text-white mb-8">
                    Terms of Service
                </h1>

                <div className="glass rounded-3xl p-8 sm:p-12 space-y-8 text-slate-300">
                    <p className="text-sm">Last Updated: {new Date().toLocaleDateString()}</p>

                    <section>
                        <h2 className="text-2xl font-bold text-white mb-4">1. Acceptance of Terms</h2>
                        <p>By accessing and using Luahana's software and services, you agree to be bound by these Terms of Service. If you do not agree to all terms and conditions, you must not use our services.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-white mb-4">2. Use of AI Services</h2>
                        <p className="mb-4">Our applications utilize Artificial Intelligence. You agree that:</p>
                        <ul className="list-disc pl-6 space-y-2">
                            <li>AI-generated content may be unpredictable or inaccurate.</li>
                            <li>You will not use our services to generate illegal, harmful, or abusive content.</li>
                            <li>You are solely responsible for how you use the output generated by our services.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-white mb-4">3. User Accounts</h2>
                        <p>You are responsible for safeguarding your account credentials. Luahana is not liable for any loss or damage arising from your failure to protect your account information.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-white mb-4">4. Limitation of Liability</h2>
                        <p>To the maximum extent permitted by law, Luahana shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of or inability to use our services or AI features.</p>
                    </section>
                </div>
            </div>
        </div>
    );
}
